name: Build and Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "fastapi[all]" sqlalchemy pytest
  
    - name: Run Tests
      run: |
        cd server
        python3 create_db.py
        pytest tests
  deploy: 
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Restart uvicorn_service
      uses: cross-the-world/ssh-pipeline@master
      with: 
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASS }}
        script: |
          cd /home/www/UpChecker
          git pull
          sudo systemctl restart uvicorn_service
